name: CI Pipeline

on:
    push:
        branches:
            - "feature/**"
    pull_request:
        branches:
            - main
            - develop

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Run code
              run: echo "Running CI pipeline..."

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: Install uv
              uses: astral-sh/setup-uv@v2
              with:
                version: "latest"

            - name: Install ruff
              uses: astral-sh/ruff-action@v3
              with:
                version: "latest"

            - name: Install dependencies
              run: uv sync

            - name: Lint code
              run: ruff check .

            - name: Run tests
              run: pytest -v -s